version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sic_mysql_db
    environment:
      MYSQL_DATABASE: sic_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  sic-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sic_app_env
    depends_on:
      - db
    volumes:
      - .:/app
      - ${APPDATA}/gcloud:/root/.config/gcloud
      - ${USERPROFILE}/.m2:/root/.m2
      - ./uploads_data:/app/safe_uploads
    environment:
      - DB_URL=jdbc:mysql://db:3306/sic_db?useSSL=false&allowPublicKeyRetrieval=true
      - DB_USER=root
      - DB_PASSWORD=root_password
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - UPLOAD_PATH=/app/safe_uploads
    ports:
     - "9090:8080"
    stdin_open: true
    tty: true

volumes:
  mysql_data: